# Server
server:
  port: 80

# Banco de dados
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logisticadb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: teu_mail@hotmail.com
    password: tua_senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        default-encoding: UTF-8
