server:
  port: 1245

spring:
  application:
    name: caminhoneiro-service
  datasource:
    url: jdbc:postgresql://localhost:5431/administracaodb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: your email
    password: your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        default-encoding: UTF-8
  ## RabbitMQ configs ##
  mq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    vhost: /
    exchange: email-exchange