# Server
server:
  port: 80

spring:
  application:
    name: app-logistica
  # Banco de dados
  datasource:
    url: jdbc:postgresql://localhost:5432/logisticadb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Email
  mail:
    host: smtp.office365.com
    port: 587
    username: your email
    password: your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        default-encoding: UTF-8
  profiles:
    active: usage_message


## RabbitMQ configs ##
mq:
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: /
  exchange: email-exchange